# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']


# Dependencies
markdown: kramdown
mathjax: true
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Contest Math
tagline:          Contest Math
description:      "A page full of exercises relating to contest math!"
url:              https://github.com/jamiecayley/contestmath
baseurl:          /contestmath/

author:
  name:           'Jamie Calley'
  url:            https://github.com/jamiecayley

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jamiecayley/contestmath
repository:       jamiecalley/contestmath
